name: E2E Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  testing:
    name: Start E2E Testing
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Store Playwright's Version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test --depth=0 | grep @playwright | sed 's/.*@//')
          echo "Playwright's Version: $PLAYWRIGHT_VERSION"
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright Browsers for Playwright's Version
        id: cache-playwright-browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright Browsers
        if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      - name: List test-results directory
        run: ls -R test-results

      - name: Upload Playwright test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 1

      - name: Upload Playwright screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: test-results/screenshots/
          retention-days: 1     

      - name: Download Playwright test results
        uses: actions/download-artifact@v3
        with:
          name: playwright-test-results
          path: downloaded-test-results
        
      - name: Download Playwright screenshots
        uses: actions/download-artifact@v3
        with:
          name: playwright-screenshots
          path: downloaded-screenshots

      - name: Unzip Playwright test results
        run: unzip downloaded-test/playwright-test-results.zip -d unzipped-test-results

      - name: Unzip Playwright screenshots
        run: unzip downloaded-screenshots/playwright-screenshots.zip -d unzipped-screenshots

      - name: Upload Summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-summary
          path: summary.html
          retention-days: 1
